### ISSUE TITLE
请问，表情识别部分也是一样的模型训练后直接统计的预测结果嘛

### ISSUE THREAD

**Issue by nswyyds** [XUJ1Er/FAER#2]

**Comment by XUJ1Er** [comment]
> 

是的，表情识别部分的预测头和属性分析部分的预测头不一样；前者是多分类，后者是二元分类任务，其余都是基于标准方法获得的结果

**Comment by nswyyds** [comment]
我是刚刚学习这部分内容，您写的很多部分我都尚未接触，请问我使用官方的convnext模型再加上您的注意力机制这部分，可以达到一定的效果嘛。因为实际上我并不会像您那样使用加载权重。

**Comment by XUJ1Er** [comment]
> 我是刚刚学习这部分内容，您写的很多部分我都尚未接触，请问我使用官方的convnext模型再加上您的注意力机制这部分，可以达到一定的效果嘛。因为实际上我并不会像您那样使用加载权重。

很明显不会，不然我也没必要花时间和金钱去进行预训练了；此外，您可以在大规模人脸数据集上进行预训练，这会显著提升模型的效果，当然，这是以时间和金钱为代价！

**Comment by nswyyds** [comment]
好的谢谢您。我再研究研究，非常感谢
